default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chutes_and_ladders_development

test:
  <<: *default
  database: chutes_and_ladders_test

production:
  <<: *default
  database: chutes_and_ladders_production
  username: chutes_and_ladders
  password: <%= ENV['CHUTES_AND_LADDERS_DATABASE_PASSWORD'] %>
