default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chutes-and-ladders_development

test:
  <<: *default
  database: chutes-and-ladders_test

production:
  <<: *default
  database: chutes-and-ladders_production
  username: chutes-and-ladders
  password: <%= ENV['CHUTES-AND-LADDERS_DATABASE_PASSWORD'] %>